plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - rubocop-rubycw

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "spec/fixtures/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "Rakefile"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - "lib/waha/resources/messages.rb"

Metrics/ParameterLists:
  Exclude:
    - "lib/waha/resources/messages.rb"
    - "lib/waha/transport/http_party.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/waha/resources/messages.rb"
    - "lib/waha/transport/http_party.rb"

Layout/LineLength:
  Exclude:
    - "waha-ruby.gemspec"

RSpec/MultipleDescribes:
  Exclude:
    - "spec/waha/gows_spec.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Gemspec/DevelopmentDependencies:
  Enabled: false
